name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      BEERKA_KEY_ALIAS: ${{ secrets.BEERKA_KEY_ALIAS }}
      BEERKA_KEY_PASSWORD: ${{ secrets.BEERKA_KEY_PASSWORD }}
      BEERKA_KEYSTORE: ${{ secrets.BEERKA_KEYSTORE }}
      BEERKA_KEYSTORE_PASSWORD: ${{ secrets.BEERKA_KEYSTORE_PASSWORD }}
      BEERKA_KEYSTORE_PATH: ${{ secrets.BEERKA_KEYSTORE_PATH }}

    steps:
      ## Checkout repository ###
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      ## Build all Build Types at once ##
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease

      ## Sign artifact##
      - name: Sign artifact
        # ID used to access action output
        id: sign_app
        uses: r0adkll/sign-android-release@master
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: BEERKA_KEY_ALIAS
          signingKeyBase64: BEERKA_KEYSTORE
          keyStorePassword: BEERKA_KEYSTORE_PASSWORD
          keyPassword: BEERKA_KEY_PASSWORD

      - name: Check signed path
        run: echo "Signed apk output = ${{steps.sign_app.outputs.signedReleaseFile}}"

      - name: Upload APK
        id: upload_apk
        uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
